"""'Updateimage4'

Revision ID: 587a77b993b1
Revises: bb0711c0b0c0
Create Date: 2023-06-20 14:47:39.100642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587a77b993b1'
down_revision = 'bb0711c0b0c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
