"""'Updateimage3'

Revision ID: bb0711c0b0c0
Revises: c425c3abb010
Create Date: 2023-06-20 14:44:24.410867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0711c0b0c0'
down_revision = 'c425c3abb010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_comment_id_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'comment_id')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('images_comment_id_fkey', 'images', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
