"""'Updateimage2'

Revision ID: c425c3abb010
Revises: e941f0b7785f
Create Date: 2023-06-20 11:27:30.185469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c425c3abb010'
down_revision = 'e941f0b7785f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
