"""'Updateimage4'

Revision ID: e072372b1900
Revises: 587a77b993b1
Create Date: 2023-06-20 21:49:57.705116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e072372b1900'
down_revision = '587a77b993b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
