"""'Updateimage1'

Revision ID: e941f0b7785f
Revises: 23feace6f53e
Create Date: 2023-06-20 11:18:41.591589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e941f0b7785f'
down_revision = '23feace6f53e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
